version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "03:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "ci"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: nix
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "03:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "flake"
    groups:
      inputs:
        patterns:
          - "*"
